# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

disk0 = './secondDisk0.vdi'
disk1 = './secondDisk1.vdi'
disk2 = './secondDisk2.vdi'
disk3 = './secondDisk3.vdi'
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.define :k8s_master do |k8sm|
    k8sm.vm.box = "ubuntu/xenial64"
    k8sm.vm.network :private_network, ip: "192.168.56.101"
    k8sm.vm.provider :virtuak8smox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "k8s_server" ]
      unless File.exist?(disk0)
        vb.customize ['createhd', '--filename', disk0, '--variant', 'Fixed', '--size', 5 * 1024]
      end
      vb.customize ['storageattach', :id,  '--storagectl', 'SCSI', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk0]
    end
    k8sm.vm.provision "shell", inline: <<-SHELL
      echo "node0" > /etc/hostname
    SHELL
    k8sm.vm.provision "shell", path: "install/configurations.sh"
    k8sm.vm.provision "shell", path: "install/docker.sh"
    #k8sm.vm.provision "shell", path: "install/compose.sh"
    k8sm.vm.provision "shell", path: "install/k8s.sh"
    k8sm.vm.provision "shell", path: "install/glusterfs.sh"
  end
  config.vm.define :k8s_node_1 do |k8sn1|
    k8sn1.vm.box = "ubuntu/xenial64"
    k8sn1.vm.network :private_network, ip: "192.168.56.102"
    k8sn1.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "512","--cpus", "1", "--name", "k8s_node_1" ]
      unless File.exist?(disk1)
        vb.customize ['createhd', '--filename', disk1, '--variant', 'Fixed', '--size', 5 * 1024]
      end
      vb.customize ['storageattach', :id,  '--storagectl', 'SCSI', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk1]
    end
    k8sn1.vm.provision "shell", inline: <<-SHELL
      echo "node1" > /etc/hostname
    SHELL
    k8sn1.vm.provision "shell", path: "install/configurations.sh"
    k8sn1.vm.provision "shell", path: "install/docker.sh"
    k8sn1.vm.provision "shell", path: "install/k8s.sh"
    k8sn1.vm.provision "shell", path: "install/glusterfs.sh"
  end
  config.vm.define :k8s_node_2 do |k8sn2|
    k8sn2.vm.box = "ubuntu/xenial64"
    k8sn2.vm.network :private_network, ip: "192.168.56.103"
    k8sn2.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "512","--cpus", "1", "--name", "k8s_node_2" ]
      unless File.exist?(disk2)
        vb.customize ['createhd', '--filename', disk2, '--variant', 'Fixed', '--size', 5 * 1024]
      end
      vb.customize ['storageattach', :id,  '--storagectl', 'SCSI', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk2]
    end
    k8sn2.vm.provision "shell", inline: <<-SHELL
      echo "node2" > /etc/hostname
    SHELL
    k8sn2.vm.provision "shell", path: "install/configurations.sh"
    k8sn2.vm.provision "shell", path: "install/docker.sh"
    k8sn2.vm.provision "shell", path: "install/k8s.sh"
    k8sn2.vm.provision "shell", path: "install/glusterfs.sh"
  end
  config.vm.define :k8s_node_3 do |k8sn3|
    k8sn3.vm.box = "ubuntu/xenial64"
    k8sn3.vm.network :private_network, ip: "192.168.56.104"
    k8sn3.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "512","--cpus", "1", "--name", "k8s_node_3" ]
      unless File.exist?(disk3)
        vb.customize ['createhd', '--filename', disk3, '--variant', 'Fixed', '--size', 5 * 1024]
      end
      vb.customize ['storageattach', :id,  '--storagectl', 'SCSI', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk3]
    end
    k8sn3.vm.provision "shell", inline: <<-SHELL
      echo "node3"> /etc/hostname
    SHELL
    k8sn3.vm.provision "shell", path: "install/configurations.sh"
    k8sn3.vm.provision "shell", path: "install/docker.sh"
    k8sn3.vm.provision "shell", path: "install/k8s.sh"
    k8sn3.vm.provision "shell", path: "install/glusterfs.sh"
  end
end
